/* tslint:disable */
/* eslint-disable */
/**
 * ue-auth
 * UEAuth is provided by <a href='https://unitedeffects.com'>United Effects LLC</a>. Copyright &#169; 2023, all rights reserved.<br><br> As a general reference, this provider implements the following OIDC endpoints. All OpenID Connect schema specific endpoints follow the pattern <code>/{group}/path</code>.<br>UE Auth identity and access endpoints follow the pattern <code>/api/{group}/path</code>. Full documentation on the OpenID Connect specification can be found here: <a href='https://openid.net/developers/specs/'>OIDC API DOCUMENTATION</a>.<br><code><br>authorization: '/{group}/auth',<br> check_session: '/{group}/session/check',<br> code_verification: '/{group}/device',<br> device_authorization: '/{group}/device/auth',<br> end_session: '/{group}/session/end',<br> introspection: '/{group}/token/introspection',<br> initial_access: '/{group}/token/initial_access',<br> jwks: '/{group}/jwks',<br> pushed_authorization_request: '/{group}/request',<br> registration: '/{group}/reg',<br> revocation: '/{group}/token/revocation',<br> token: '/{group}/token',<br> userinfo: '/{group}/me'</code><br><br> <small>Not all of the above endpoints are detailed with contracts in this API documentation. Please reference the <a href='https://openid.net/developers/specs/'>OIDC</a> docs for any path specs not shown.</small><br><br> <h2>Query and Patch Standards</h2>This API uses <a href='https://www.odata.org/documentation/'>oData</a> and <a href='http://jsonpatch.com/'>JSON Patch</a> as standards for most paginated GET and PATCH methods. You may wish to review these standards.
 *
 * OpenAPI spec version: 1.32.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgConfigOptionsFederate } from './ag-config-options-federate';
import { AgConfigOptionsLogEventGroups } from './ag-config-options-log-event-groups';
import { AgConfigOptionsMfaChallenge } from './ag-config-options-mfa-challenge';
import { AgConfigOptionsTtl } from './ag-config-options-ttl';
import { AgConfigOptionsUi } from './ag-config-options-ui';
/**
 * these configurations alter how OIDC is processed
 * @export
 * @interface AgConfigOptions
 */
export interface AgConfigOptions {
    /**
     * 
     * @type {AgConfigOptionsLogEventGroups}
     * @memberof AgConfigOptions
     */
    logEventGroups?: AgConfigOptionsLogEventGroups;
    /**
     * 
     * @type {AgConfigOptionsTtl}
     * @memberof AgConfigOptions
     */
    ttl?: AgConfigOptionsTtl;
    /**
     * when true, this ensures that only verified accounts can complete a login
     * @type {boolean}
     * @memberof AgConfigOptions
     */
    requireVerified?: boolean;
    /**
     * when true, this sends a notification to a new account to verify automatically - MUST have notifications enabled first
     * @type {boolean}
     * @memberof AgConfigOptions
     */
    autoVerify?: boolean;
    /**
     * when true, this allows magic link emails for login - MUST have notification enabled first
     * @type {boolean}
     * @memberof AgConfigOptions
     */
    passwordLessSupport?: boolean;
    /**
     * when true, this allows enables the centrally served password reset UI to be accessed publicaly
     * @type {boolean}
     * @memberof AgConfigOptions
     */
    centralPasswordReset?: boolean;
    /**
     * these are scopes that will be availabl to all clients within your authgroup oidc provider
     * @type {Array<string>}
     * @memberof AgConfigOptions
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AgConfigOptions
     */
    acrValues?: Array<string>;
    /**
     * activates device flow for devices without browsers. EXPERIENCE NOT FULLY IMPLEMENTED
     * @type {boolean}
     * @memberof AgConfigOptions
     */
    deviceFlow?: boolean;
    /**
     * when this is true, only pkce logins are possible
     * @type {boolean}
     * @memberof AgConfigOptions
     */
    pkceRequired?: boolean;
    /**
     * 
     * @type {AgConfigOptionsMfaChallenge}
     * @memberof AgConfigOptions
     */
    mfaChallenge?: AgConfigOptionsMfaChallenge;
    /**
     * 
     * @type {AgConfigOptionsFederate}
     * @memberof AgConfigOptions
     */
    federate?: AgConfigOptionsFederate;
    /**
     * 
     * @type {AgConfigOptionsUi}
     * @memberof AgConfigOptions
     */
    ui?: AgConfigOptionsUi;
}
